USE `analytics project`;
-- Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(`Purchase Amount (USD)`) as revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select `ï»¿Customer ID`, `purchase amount (USD)` 
from customer 
where `discount applied` = 'Yes' and `purchase amount (USD)` >= (select AVG(`purchase amount (USD)`) 
from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select `item purchased`, ROUND(AVG(`review rating`), 2) as Average_Product_Rating
from customer
group by `item purchased`
order by avg(`review rating`) desc
limit 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select `shipping type`, ROUND(AVG(`purchase amount (USD)`), 2)
from customer
where `shipping type` in ('Standard','Express')
group by `shipping type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT `Subscription Status`,
       COUNT(*) AS total_customers,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       ROUND(SUM(`Purchase Amount (USD)`), 2) AS total_revenue
FROM customer
GROUP BY `Subscription Status`
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY `Item Purchased`
ORDER BY `discount_rate` DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT `ï»¿Customer ID`, `previous purchases`,
CASE 
    WHEN `previous purchases` = 1 THEN 'New'
    WHEN `previous purchases` BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           `item purchased`,
           COUNT(`ï»¿Customer ID`) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(`ï»¿Customer ID`) DESC) AS item_rank
    FROM customer
    GROUP BY category, `item purchased`
)
SELECT item_rank,category, `item purchased`, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `subscription status`,
       COUNT(`ï»¿Customer ID`) AS repeat_buyers
FROM customer
WHERE `previous purchases` > 5
GROUP BY `subscription status`;

--------------------------------------------------------------
ALTER TABLE customer
ADD COLUMN age_group VARCHAR(20);

SET SQL_SAFE_UPDATES = 0;

UPDATE customer
SET age_group =
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN 'Young Adult'
        WHEN Age BETWEEN 26 AND 40 THEN 'Adult'
        WHEN Age BETWEEN 41 AND 60 THEN 'Middle-aged'
        ELSE 'Senior'
    END;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(`purchase amount (USD)`) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
